# Cargo.toml
[package]
name = "lightci-core"
version = "0.1.0"
edition = "2021"
description = "Core pipeline engine for LightCI"

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
uuid = { version = "1.7.0", features = ["v4", "serde"] }
chrono = { version = "0.4.34", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_yaml = "0.9.32"
async-trait = "0.1.77"
thiserror = "1.0.57"
tonic = "0.11.0"
prost = "0.12.3"
prost-types = "0.12.3"
futures = "0.3.30"
bytes = "1.5.0"
sqlx = { version = "0.7.3", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
git2 = "0.18.2"
tempfile = "3.10.1"
rust-crypto = "0.2.36"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
env_logger = "0.10"
log = "0.4"
dotenv = "0.15"
tokio-stream = "0.1.17"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.10"
pretty_assertions = "1.4"

[build-dependencies]
tonic-build = "0.11.0"
