[package]
name = "lightci_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
lightci-core = { path = "../core" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
uuid = { version = "1.7", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
tokio-stream = "0.1"
dirs = "5.0"
colored = "2.0"
tabwriter = "1.3"
tempfile = "3.8"

[dev-dependencies]
pretty_assertions = "1.4"
tempfile = "3.8"